KEYBOX_URL="https://raw.githubusercontent.com/WajahatNaeem056/jerrybin/main/key"
ATTESTATION_URL="https://raw.githubusercontent.com/WajahatNaeem056/jerrybin/main/attestation"
LATEST_KEYBOX_URL="https://raw.githubusercontent.com/WajahatNaeem056/jerrybin/main/latest_keybox"
GOOGLE_REVOCATION_URL="https://android.googleapis.com/attestation/status?encrypted=1"
HMA_CONFIG_URL="https://raw.githubusercontent.com/WajahatNaeem056/jerrybin/main/hma_config"
